In [1]:
import pandas as pd
import numpy as np

In [2]:
hh = pd.read_csv(r'17家金-hh.csv')
ind = pd.read_csv(r'17家金-ind.csv')
master = pd.read_csv(r'17家金-master-city.csv')
sheet = pd.read_excel(r'变量汇总.xlsx', sheet_name='v4')

C:\Users\chen\AppData\Local\Temp\ipykernel_5744\2797064380.py:1: DtypeWarning: Columns (65,88,118,119,121,126,131,157,205,226,245,263,268,289,308,323,326,331,351,370,381,385,388,413,432,443,447,450,506,510,513,654,660,688,704,712,721,736,741,742,743,744,755,756,761,763,779,800,840,853,868,869,870,871,872,873,874,875,942,943,983,1008,1014,1015,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1048,1049,1050,1051,1052,1053,1054,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1076,1077,1078,1079,1080,1081,1082,1084,1086,1087,1093,1094,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1116,1117,1118,1119,1120,1121,1122,1123,1124,1126,1127,1128,1130,1131,1133,1134,1135,1136,1137,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1156,1161,1162,1163,1166,1167,1168,1169,1170,1171,1172,1173,1174,1189,1190,1191,1192,1193,2444) have mixed types. Specify dtype option on import or set low_memory=False.
  hh = pd.read_csv(r'17家金-hh.csv')
C:\Users\chen\AppData\Local\Temp\ipykernel_5744\2797064380.py:2: DtypeWarning: Columns (49,50,51,52,78,117,120,122,125,128,129,130,131,132,137,139,140,141,142,145,147,162,207,221,222,223) have mixed types. Specify dtype option on import or set low_memory=False.
  ind = pd.read_csv(r'17家金-ind.csv')

# 1.   基本处理（包括合并数据、重命名及数据类型变换）

## 1.1合并数据

In [3]:
from DataProcessor import processor1

In [4]:
data = processor1.get_all_data(hh_data=hh, ind_data=ind, master_data=master)

In [5]:
data

,hhcid_2017,hhid,hhid_2011,hhid_2013,hhid_2015,hhid_2017,track,j1001,a1100,a1101,...,f1005_imp_dummy,unique_id,prov_CHN,province,rural,city_lab,county_lab,swgt_h,swgt_p,pab
0,com2017000668,2017000001,NaN,NaN,NaN,2017000001,0,6.0,NaN,NaN,...,NaN,2017000001_2,广东省,44,1,35,68,9760,16068,a
1,com2017000046,2013013417,NaN,2.013013e+09,2.015018e+09,2017000002,1,2.0,1.0,NaN,...,0.0,2013013417_1,福建省,35,0,14,24,23061,14910,a
2,com2017000193,2017000003,NaN,NaN,NaN,2017000003,0,1.0,NaN,NaN,...,NaN,2017000003_1,广西壮族自治区,45,0,39,73,3385,2402,a
3,com2017000575,2013012670,NaN,2.013013e+09,2.015017e+09,2017000004,1,6.0,1.0,NaN,...,NaN,2013012670_2,福建省,35,1,12,22,2572,4234,b
4,com2017000767,2013020230,NaN,2.013020e+09,2.015028e+09,2017000005,1,6.0,1.0,NaN,...,NaN,2013020230_1,广东省,44,1,26,45,755,751,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,com2017000952,2017040007,NaN,NaN,NaN,2017040007,0,6.0,NaN,NaN,...,NaN,2017040007_1,河南省,41,1,57,112,24864,36896,b
39166,com2017000889,2015026785,NaN,NaN,2.015027e+09,2017040008,1,2.0,1.0,NaN,...,NaN,2015026785_1,广东省,44,0,33,62,24234,17728,b
39167,com2017000444,2017040009,NaN,NaN,NaN,2017040009,0,1.0,NaN,NaN,...,NaN,2017040009_1,山东省,37,0,132,248,8427,10645,a
39168,com2017001279,201100379,201100379.0,2.013001e+09,2.015001e+09,2017040010,1,1.0,1.0,NaN,...,0.0,201100379_1,北京市,11,0,10,17,4509,3127,a
39169,com2017000683,2017040011,NaN,NaN,NaN,2017040011,0,5.0,NaN,NaN,...,NaN,2017040011_2,河南省,41,0,61,118,32805,34167,a

## 1.2重命名

In [6]:
df_res = processor1.rename_columns(data, sheet)

重命名完成

In [7]:
list(df_res.columns)

['hhid',
 '股票',
 '基金',
 '金融理财',
 '借出款',
 '现金量',
 '现金量it',
 '活期存款量',
 '活期存款量it',
 '定期存款量',
 '定期存款量it',
 '股票量',
 '股票量it',
 '基金量',
 '基金量it',
 '互联网理财量',
 '互联网理财量it',
 '金融理财量',
 '金融理财量it',
 '债券量',
 '债券量it',
 '衍生品量',
 '衍生品量it',
 '非人民币资产量',
 '非人民币资产量it',
 '黄金量',
 '黄金量it',
 '其他金融资产量',
 '其他金融资产量it',
 '借出款量',
 '借出款量it',
 '性别',
 '年龄',
 '婚姻',
 '文化程度',
 '户口（农村）',
 '党员',
 '是否工作',
 '健康',
 '工作性质',
 '是否使用互联网',
 '信用卡持有',
 '借记卡持有',
 '手机支付持有',
 '是否关注经济金融信息',
 '利率计算',
 '膨胀计算',
 '股票风险对比',
 '基金风险对比',
 '幸福度',
 '风险态度',
 '投资经验1',
 '家庭成员中是否有政府或事业单位人员',
 '家庭总资产',
 '家庭总消费',
 '家庭负债',
 '家庭总收入',
 '医保比例',
 '养老保险比例',
 '失业保险',
 '住房公积金',
 '工商业经营生产活动',
 '家庭是否贫困',
 '是否自有住房',
 '农业机械价值',
 '车辆价值',
 '车辆价值it',
 '房产价值',
 '房产价值it',
 '土地价值',
 '工商业价值',
 '工商业价值it',
 '工资收入',
 '工资收入it',
 '农业收入',
 '父母转移收入',
 '父母2转移收入',
 '其他转移收入',
 '工商业收入',
 '工商业收入it',
 '食物支出',
 '教育培训支出',
 '衣着支出',
 '居住支出',
 '医疗保健支出',
 '医疗保健支出it',
 '旅游支出',
 '旅游支出it',
 '日用品支出',
 '文娱支出',
 '网购支出',
 '金融负债',
 '金融负债it',
 '农业负债',
 '工商业负债',
 '工商业负债it',
 '房屋负债',
 '房屋负债it',
 '车辆负债',
 '车辆负债it',
 '其他非金融负债',
 '其他非金融负债it',
 '教育负债',
 '教育负债it',
 '医疗负债',
 '医疗负债it',
 '其他负债',
 '其他负债it',
 '城乡',
 '省份',
 '城市编码',
 '区县编码',
 '基金类型']

## 1.3数据类型转换

In [8]:
df3 = processor1.base_processing(df_res, ['城乡', '省份', '城市编码','区县编码','手机支付持有','基金类型'])

# 2.数据填充

In [9]:
from DataProcessor import filling

## 2.1逻辑填充

In [11]:
df4 = filling.logit_filling(df=df3, sheet=sheet)

In [12]:
df4

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,教育负债it,医疗负债,医疗负债it,其他负债,其他负债it,城乡,省份,城市编码,区县编码,基金类型
0,2017000001,2.0,2.0,2.0,2.0,300.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,广东省,35,68,NaN
1,2013013417,2.0,2.0,2.0,2.0,25000.0,NaN,3204.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,福建省,14,24,NaN
2,2017000003,2.0,2.0,2.0,2.0,1700.0,NaN,5500.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,广西壮族自治区,39,73,NaN
3,2013012670,2.0,2.0,2.0,2.0,2000.0,NaN,7000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,福建省,12,22,NaN
4,2013020230,2.0,2.0,2.0,2.0,1000.0,NaN,26.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,广东省,26,45,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,2.0,2.0,2.0,2.0,1000.0,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,河南省,57,112,NaN
39166,2015026785,2.0,2.0,2.0,2.0,3000.0,NaN,5000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,广东省,33,62,NaN
39167,2017040009,2.0,2.0,2.0,1.0,10000.0,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,山东省,132,248,NaN
39168,201100379,2.0,1.0,1.0,2.0,10000.0,NaN,15000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,北京市,10,17,4.0
39169,2017040011,2.0,2.0,2.0,2.0,0.0,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,河南省,61,118,NaN

# 2.2 通过范围it填数值

In [13]:
df5 = filling.pre_it_filling(df4,sheet)

现金量it的范围变量现金量填充完毕
互联网理财量it的范围变量互联网理财量填充完毕
金融负债it的范围变量金融负债填充完毕
其他非金融负债it的范围变量其他非金融负债填充完毕
活期存款量it的范围变量活期存款量填充完毕
定期存款量it的范围变量定期存款量填充完毕
股票量it的范围变量股票量填充完毕
基金量it的范围变量基金量填充完毕
债券量it的范围变量债券量填充完毕
衍生品量it的范围变量衍生品量填充完毕
黄金量it的范围变量黄金量填充完毕
其他金融资产量it的范围变量其他金融资产量填充完毕
工商业收入it的范围变量工商业收入填充完毕
工商业负债it的范围变量工商业负债填充完毕
车辆负债it的范围变量车辆负债填充完毕
教育负债it的范围变量教育负债填充完毕
医疗负债it的范围变量医疗负债填充完毕
其他负债it的范围变量其他负债填充完毕
金融理财量it的范围变量金融理财量填充完毕
非人民币资产量it的范围变量非人民币资产量填充完毕
借出款量it的范围变量借出款量填充完毕
车辆价值it的范围变量车辆价值填充完毕
工资收入it的范围变量工资收入填充完毕
工商业价值it的范围变量工商业价值填充完毕
医疗保健支出it的范围变量医疗保健支出填充完毕
旅游支出it的范围变量旅游支出填充完毕
房产价值it的范围变量房产价值填充完毕
房屋负债it的范围变量房屋负债填充完毕

In [14]:
df5

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,教育负债it,医疗负债,医疗负债it,其他负债,其他负债it,城乡,省份,城市编码,区县编码,基金类型
0,2017000001,2.0,2.0,2.0,2.0,300.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,广东省,35,68,NaN
1,2013013417,2.0,2.0,2.0,2.0,25000.0,NaN,3204.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,福建省,14,24,NaN
2,2017000003,2.0,2.0,2.0,2.0,1700.0,NaN,5500.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,广西壮族自治区,39,73,NaN
3,2013012670,2.0,2.0,2.0,2.0,2000.0,NaN,7000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,福建省,12,22,NaN
4,2013020230,2.0,2.0,2.0,2.0,1000.0,NaN,26.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,广东省,26,45,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,2.0,2.0,2.0,2.0,1000.0,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1,河南省,57,112,NaN
39166,2015026785,2.0,2.0,2.0,2.0,3000.0,NaN,5000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,广东省,33,62,NaN
39167,2017040009,2.0,2.0,2.0,1.0,10000.0,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,山东省,132,248,NaN
39168,201100379,2.0,1.0,1.0,2.0,10000.0,NaN,15000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,北京市,10,17,4.0
39169,2017040011,2.0,2.0,2.0,2.0,0.0,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,河南省,61,118,NaN

## 2.3 常规填充

In [14]:
df6 = filling.norm_filling(df5,sheet)

In [15]:
df6

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,教育负债it,医疗负债,医疗负债it,其他负债,其他负债it,城乡,省份,城市编码,区县编码,基金类型
0,2017000001,2.0,2.0,2.0,2.0,300.0,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,1,广东省,35,68,1
1,2013013417,2.0,2.0,2.0,2.0,25000.0,NaN,3204.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,0,福建省,14,24,1
2,2017000003,2.0,2.0,2.0,2.0,1700.0,NaN,5500.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,0,广西壮族自治区,39,73,1
3,2013012670,2.0,2.0,2.0,2.0,2000.0,NaN,7000.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,1,福建省,12,22,1
4,2013020230,2.0,2.0,2.0,2.0,1000.0,NaN,26.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,1,广东省,26,45,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,2.0,2.0,2.0,2.0,1000.0,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,1,河南省,57,112,1
39166,2015026785,2.0,2.0,2.0,2.0,3000.0,NaN,5000.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,0,广东省,33,62,1
39167,2017040009,2.0,2.0,2.0,1.0,10000.0,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,0,山东省,132,248,1
39168,201100379,2.0,1.0,1.0,2.0,10000.0,NaN,15000.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,0,北京市,10,17,4.0
39169,2017040011,2.0,2.0,2.0,2.0,0.0,NaN,0.0,NaN,0.0,...,NaN,0.0,NaN,0.0,NaN,0,河南省,61,118,1

## 2.4 通过数值填范围

In [16]:
df7 = filling.to_it(df6,sheet)

现金量的范围变量现金量it填充完毕
互联网理财量的范围变量互联网理财量it填充完毕
金融负债的范围变量金融负债it填充完毕
其他非金融负债的范围变量其他非金融负债it填充完毕
活期存款量的范围变量活期存款量it填充完毕
定期存款量的范围变量定期存款量it填充完毕
股票量的范围变量股票量it填充完毕
基金量的范围变量基金量it填充完毕
债券量的范围变量债券量it填充完毕
衍生品量的范围变量衍生品量it填充完毕
黄金量的范围变量黄金量it填充完毕
其他金融资产量的范围变量其他金融资产量it填充完毕
工商业收入的范围变量工商业收入it填充完毕
工商业负债的范围变量工商业负债it填充完毕
车辆负债的范围变量车辆负债it填充完毕
教育负债的范围变量教育负债it填充完毕
医疗负债的范围变量医疗负债it填充完毕
其他负债的范围变量其他负债it填充完毕
金融理财量的范围变量金融理财量it填充完毕
非人民币资产量的范围变量非人民币资产量it填充完毕
借出款量的范围变量借出款量it填充完毕
车辆价值的范围变量车辆价值it填充完毕
工资收入的范围变量工资收入it填充完毕
工商业价值的范围变量工商业价值it填充完毕
医疗保健支出的范围变量医疗保健支出it填充完毕
旅游支出的范围变量旅游支出it填充完毕
房产价值的范围变量房产价值it填充完毕
房屋负债的范围变量房屋负债it填充完毕

In [17]:
df7

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,教育负债it,医疗负债,医疗负债it,其他负债,其他负债it,城乡,省份,城市编码,区县编码,基金类型
0,2017000001,2.0,2.0,2.0,2.0,300.0,1,0.0,1,0.0,...,1,0.0,1,0.0,1,1,广东省,35,68,1
1,2013013417,2.0,2.0,2.0,2.0,25000.0,4,3204.0,1,0.0,...,1,0.0,1,0.0,1,0,福建省,14,24,1
2,2017000003,2.0,2.0,2.0,2.0,1700.0,1,5500.0,1,0.0,...,1,0.0,1,0.0,1,0,广西壮族自治区,39,73,1
3,2013012670,2.0,2.0,2.0,2.0,2000.0,1,7000.0,1,0.0,...,1,0.0,1,0.0,1,1,福建省,12,22,1
4,2013020230,2.0,2.0,2.0,2.0,1000.0,1,26.0,1,0.0,...,1,0.0,1,0.0,1,1,广东省,26,45,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,2.0,2.0,2.0,2.0,1000.0,1,0.0,1,0.0,...,1,0.0,1,0.0,1,1,河南省,57,112,1
39166,2015026785,2.0,2.0,2.0,2.0,3000.0,1,5000.0,1,0.0,...,1,0.0,1,0.0,1,0,广东省,33,62,1
39167,2017040009,2.0,2.0,2.0,1.0,10000.0,2,0.0,1,0.0,...,1,0.0,1,0.0,1,0,山东省,132,248,1
39168,201100379,2.0,1.0,1.0,2.0,10000.0,2,15000.0,2,0.0,...,1,0.0,1,0.0,1,0,北京市,10,17,4.0
39169,2017040011,2.0,2.0,2.0,2.0,0.0,1,0.0,1,0.0,...,1,0.0,1,0.0,1,0,河南省,61,118,1

## 2.5 查看缺失值

In [18]:
filling.check_miss(df7, [0.2,0.5])

无缺失变量

# 3. 变量合并

In [35]:
from DataProcessor import varbin

## 3.1 有序数据分箱

In [36]:
varbin.DataBin(df7,'风险态度','zidingyi',[0,2,3,6])

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,医疗负债,医疗负债it,其他负债,其他负债it,城乡,省份,城市编码,区县编码,基金类型,风险态度_箱
0,2017000001,2.0,2.0,2.0,2.0,300.0,1,0.0,1,0.0,...,0.0,1,0.0,1,1,广东省,35,68,1,3
1,2013013417,2.0,2.0,2.0,2.0,25000.0,4,3204.0,1,0.0,...,0.0,1,0.0,1,0,福建省,14,24,1,3
2,2017000003,2.0,2.0,2.0,2.0,1700.0,1,5500.0,1,0.0,...,0.0,1,0.0,1,0,广西壮族自治区,39,73,1,2
3,2013012670,2.0,2.0,2.0,2.0,2000.0,1,7000.0,1,0.0,...,0.0,1,0.0,1,1,福建省,12,22,1,3
4,2013020230,2.0,2.0,2.0,2.0,1000.0,1,26.0,1,0.0,...,0.0,1,0.0,1,1,广东省,26,45,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,2.0,2.0,2.0,2.0,1000.0,1,0.0,1,0.0,...,0.0,1,0.0,1,1,河南省,57,112,1,3
39166,2015026785,2.0,2.0,2.0,2.0,3000.0,1,5000.0,1,0.0,...,0.0,1,0.0,1,0,广东省,33,62,1,3
39167,2017040009,2.0,2.0,2.0,1.0,10000.0,2,0.0,1,0.0,...,0.0,1,0.0,1,0,山东省,132,248,1,1
39168,201100379,2.0,1.0,1.0,2.0,10000.0,2,15000.0,2,0.0,...,0.0,1,0.0,1,0,北京市,10,17,4.0,3
39169,2017040011,2.0,2.0,2.0,2.0,0.0,1,0.0,1,0.0,...,0.0,1,0.0,1,0,河南省,61,118,1,3

In [37]:
df8 = varbin.DataBin_2(df7,sheet)

In [38]:
df8

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,城市编码,区县编码,基金类型,风险态度_箱,文化程度_箱,户口（农村）_箱,健康_箱,借记卡持有_箱,是否关注经济金融信息_箱,幸福度_箱
0,2017000001,2.0,2.0,2.0,2.0,300.0,1,0.0,1,0.0,...,35,68,1,3,1,1,1,1,2,1
1,2013013417,2.0,2.0,2.0,2.0,25000.0,4,3204.0,1,0.0,...,14,24,1,3,1,2,3,2,2,2
2,2017000003,2.0,2.0,2.0,2.0,1700.0,1,5500.0,1,0.0,...,39,73,1,2,1,2,2,2,2,1
3,2013012670,2.0,2.0,2.0,2.0,2000.0,1,7000.0,1,0.0,...,12,22,1,3,1,1,2,2,2,2
4,2013020230,2.0,2.0,2.0,2.0,1000.0,1,26.0,1,0.0,...,26,45,1,3,1,1,1,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,2.0,2.0,2.0,2.0,1000.0,1,0.0,1,0.0,...,57,112,1,3,1,1,1,2,2,2
39166,2015026785,2.0,2.0,2.0,2.0,3000.0,1,5000.0,1,0.0,...,33,62,1,3,1,1,3,2,2,1
39167,2017040009,2.0,2.0,2.0,1.0,10000.0,2,0.0,1,0.0,...,132,248,1,1,2,1,1,2,2,1
39168,201100379,2.0,1.0,1.0,2.0,10000.0,2,15000.0,2,0.0,...,10,17,4.0,3,1,2,1,2,2,1
39169,2017040011,2.0,2.0,2.0,2.0,0.0,1,0.0,1,0.0,...,61,118,1,3,1,2,3,2,2,2

## 3.2 特殊变量合并

In [39]:
# 特殊变量合并
marriage = ['婚姻',{1:0,2:1,3:1,4:0,5:0,6:0,7:1}]
lilv = ['利率计算',{1:0,2:1,3:0,4:0,5:0,6:0}]
pengzhang = ['膨胀计算',{1:1,2:0,3:0,4:0,5:0,6:0}]
gupiao = ['股票风险对比',{1:0,2:1,3:0,4:0,5:0,6:0}]
jijin = ['基金风险对比',{1:1,2:0,3:0,4:0,5:0,6:0}]
zhengfu = ['家庭成员中是否有政府或事业单位人员',{1:1,2:0,3:0,4:0,5.0:0,6:0,7:0,8:0,7777:0}]

merge_lists = [marriage,lilv, pengzhang, gupiao, jijin, zhengfu]

df9 = varbin.Merge_value(df8,merge_lists)

In [40]:
df9

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,城市编码,区县编码,基金类型,风险态度_箱,文化程度_箱,户口（农村）_箱,健康_箱,借记卡持有_箱,是否关注经济金融信息_箱,幸福度_箱
0,2017000001,2.0,2.0,2.0,2.0,300.0,1,0.0,1,0.0,...,35,68,1,3,1,1,1,1,2,1
1,2013013417,2.0,2.0,2.0,2.0,25000.0,4,3204.0,1,0.0,...,14,24,1,3,1,2,3,2,2,2
2,2017000003,2.0,2.0,2.0,2.0,1700.0,1,5500.0,1,0.0,...,39,73,1,2,1,2,2,2,2,1
3,2013012670,2.0,2.0,2.0,2.0,2000.0,1,7000.0,1,0.0,...,12,22,1,3,1,1,2,2,2,2
4,2013020230,2.0,2.0,2.0,2.0,1000.0,1,26.0,1,0.0,...,26,45,1,3,1,1,1,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,2.0,2.0,2.0,2.0,1000.0,1,0.0,1,0.0,...,57,112,1,3,1,1,1,2,2,2
39166,2015026785,2.0,2.0,2.0,2.0,3000.0,1,5000.0,1,0.0,...,33,62,1,3,1,1,3,2,2,1
39167,2017040009,2.0,2.0,2.0,1.0,10000.0,2,0.0,1,0.0,...,132,248,1,1,2,1,1,2,2,1
39168,201100379,2.0,1.0,1.0,2.0,10000.0,2,15000.0,2,0.0,...,10,17,4.0,3,1,2,1,2,2,1
39169,2017040011,2.0,2.0,2.0,2.0,0.0,1,0.0,1,0.0,...,61,118,1,3,1,2,3,2,2,2

# 4. onehot

In [41]:
from DataProcessor import onehot

## 4.1  二元变量处理（12转10）

In [42]:
df10 = onehot.binary_trans(df9,sheet)

In [43]:
df10

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,城市编码,区县编码,基金类型,风险态度_箱,文化程度_箱,户口（农村）_箱,健康_箱,借记卡持有_箱,是否关注经济金融信息_箱,幸福度_箱
0,2017000001,0.0,0.0,0.0,0.0,300.0,1,0.0,1,0.0,...,35,68,1,3,1,1,1,1,0,1
1,2013013417,0.0,0.0,0.0,0.0,25000.0,4,3204.0,1,0.0,...,14,24,1,3,1,0,3,2,0,2
2,2017000003,0.0,0.0,0.0,0.0,1700.0,1,5500.0,1,0.0,...,39,73,1,2,1,0,2,2,0,1
3,2013012670,0.0,0.0,0.0,0.0,2000.0,1,7000.0,1,0.0,...,12,22,1,3,1,1,2,2,0,2
4,2013020230,0.0,0.0,0.0,0.0,1000.0,1,26.0,1,0.0,...,26,45,1,3,1,1,1,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,0.0,0.0,0.0,0.0,1000.0,1,0.0,1,0.0,...,57,112,1,3,1,1,1,2,0,2
39166,2015026785,0.0,0.0,0.0,0.0,3000.0,1,5000.0,1,0.0,...,33,62,1,3,1,1,3,2,0,1
39167,2017040009,0.0,0.0,0.0,1.0,10000.0,2,0.0,1,0.0,...,132,248,1,1,2,1,1,2,0,1
39168,201100379,0.0,1.0,1.0,0.0,10000.0,2,15000.0,2,0.0,...,10,17,4.0,3,1,0,1,2,0,1
39169,2017040011,0.0,0.0,0.0,0.0,0.0,1,0.0,1,0.0,...,61,118,1,3,1,0,3,2,0,2

## 4.2 多选onehot

In [44]:
df11 = onehot.to_binary(df10,sheet)
df11['电脑支付持有'] = df11['手机支付持有_bn_3'].apply(lambda x : 1 if x>0 else 0)
df11['手机支付持有'] = df11['手机支付持有_bn_4'].apply(lambda x : 1 if x>0 else 0)

['手机支付持有_bn_1', '手机支付持有_bn_2', '手机支付持有_bn_3', '手机支付持有_bn_4', '手机支付持有_bn_7777']

In [45]:
df11

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,健康_箱,借记卡持有_箱,是否关注经济金融信息_箱,幸福度_箱,手机支付持有_bn_1,手机支付持有_bn_2,手机支付持有_bn_3,手机支付持有_bn_4,手机支付持有_bn_7777,电脑支付持有
0,2017000001,0.0,0.0,0.0,0.0,300.0,1,0.0,1,0.0,...,1,1,0,1,1,0,0,0,0,0
1,2013013417,0.0,0.0,0.0,0.0,25000.0,4,3204.0,1,0.0,...,3,2,0,2,1,0,0,0,1,0
2,2017000003,0.0,0.0,0.0,0.0,1700.0,1,5500.0,1,0.0,...,2,2,0,1,1,0,0,0,0,0
3,2013012670,0.0,0.0,0.0,0.0,2000.0,1,7000.0,1,0.0,...,2,2,0,2,1,0,0,0,0,0
4,2013020230,0.0,0.0,0.0,0.0,1000.0,1,26.0,1,0.0,...,1,2,0,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,0.0,0.0,0.0,0.0,1000.0,1,0.0,1,0.0,...,1,2,0,2,1,0,0,0,0,0
39166,2015026785,0.0,0.0,0.0,0.0,3000.0,1,5000.0,1,0.0,...,3,2,0,1,1,1,1,1,0,1
39167,2017040009,0.0,0.0,0.0,1.0,10000.0,2,0.0,1,0.0,...,1,2,0,1,0,0,0,1,0,0
39168,201100379,0.0,1.0,1.0,0.0,10000.0,2,15000.0,2,0.0,...,1,2,0,1,1,0,1,1,0,1
39169,2017040011,0.0,0.0,0.0,0.0,0.0,1,0.0,1,0.0,...,3,2,0,2,1,0,0,0,0,0

# 5. 新变量生成

## 5.1 家庭占比变量

### 由于三个表格拼接的时会因为id的匹配掉部分数据，为保证计算真实性，用的原始ind数据进行计算的。

In [46]:
ind.replace(['.d','.r','.e','.n'],np.nan,inplace=True)
nvar = ['a2005','a2003', 'a2025b', 'a3106', 'f1001a', 'f2001a', 'f3001', 'f4001']
for i in nvar:
        ind[i] = ind[i].apply(lambda x:float(x) if not pd.isnull(x) else x)

In [47]:
tmp = ind.groupby('hhid')['pline'].count().reset_index().rename({'pline':'家庭规模'},axis=1)
laonian = ind.loc[(ind['a2005']<=1957),:].groupby(['hhid'])['a2005'].count().reset_index().rename({'a2005':'家中老人数量'},axis=1)
xiaohai = ind.loc[(ind['a2005']>=1999),:].groupby(['hhid'])['a2005'].count().reset_index().rename({'a2005':'家中小孩数量'},axis=1)
nanxing = ind.loc[(ind['a2003'] == 1),:].groupby(['hhid'])['a2003'].count().reset_index().rename({'a2003':'男性数量'},axis=1)
jiankang = ind.loc[(ind['a2025b']>= 4 ),:].groupby(['hhid'])['a2025b'].count().reset_index().rename({'a2025b':'不健康人数'},axis=1)
zhengfu = ind.loc[(ind['a3106'] == 1 ),:].groupby(['hhid'])['a3106'].count().reset_index().rename({'a3106':'政府工作人员'},axis=1)
yanglao = ind.loc[(ind['f1001a'] != 7788 )&(pd.notna(ind['f1001a'])),:].groupby(['hhid'])['f1001a'].count().reset_index().rename({'f1001a':'养老保险量'},axis=1)
yiliao = ind.loc[(ind['f2001a'] != 7788 )&(pd.notna(ind['f2001a'])),:].groupby(['hhid'])['f2001a'].count().reset_index().rename({'f2001a':'医疗保险量'},axis=1)
shiye = ind.loc[(ind['f3001'] == 1 )&(pd.notna(ind['f3001'])),:].groupby(['hhid'])['f3001'].count().reset_index().rename({'f3001':'失业保险量'},axis=1)
gongjijin = ind.loc[(ind['f4001'] == 1 )&(pd.notna(ind['f4001'])),:].groupby(['hhid'])['f4001'].count().reset_index().rename({'f4001':'住房公积金量'},axis=1)

In [48]:
listdata = [laonian,xiaohai, nanxing, jiankang, zhengfu, yanglao, yiliao, shiye, gongjijin]
for i in listdata:
    tmp = pd.merge(tmp,i,left_on='hhid',right_on='hhid',how='left')
tmp.fillna(0,inplace=True)

zhanbilist = [ '家中老人数量','家中小孩数量','男性数量','不健康人数','政府工作人员','养老保险量','医疗保险量','失业保险量','住房公积金量']
for i in zhanbilist:
    tmp[i+'占比'] = tmp[i]/tmp['家庭规模']

In [49]:
df12 = pd.merge(df11,tmp,left_on='hhid',right_on='hhid',how='left')

In [50]:
df12

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,住房公积金量,家中老人数量占比,家中小孩数量占比,男性数量占比,不健康人数占比,政府工作人员占比,养老保险量占比,医疗保险量占比,失业保险量占比,住房公积金量占比
0,2017000001,0.0,0.0,0.0,0.0,300.0,1,0.0,1,0.0,...,0.0,0.000000,0.000000,0.500000,0.000000,0.00,0.00,1.00,0.000000,0.000000
1,2013013417,0.0,0.0,0.0,0.0,25000.0,4,3204.0,1,0.0,...,0.0,0.500000,0.000000,0.500000,0.250000,0.00,0.75,1.00,0.000000,0.000000
2,2017000003,0.0,0.0,0.0,0.0,1700.0,1,5500.0,1,0.0,...,0.0,0.000000,0.000000,0.500000,0.000000,0.00,1.00,1.00,0.500000,0.000000
3,2013012670,0.0,0.0,0.0,0.0,2000.0,1,7000.0,1,0.0,...,0.0,0.000000,0.500000,0.750000,0.000000,0.00,0.50,0.75,0.000000,0.000000
4,2013020230,0.0,0.0,0.0,0.0,1000.0,1,26.0,1,0.0,...,0.0,0.000000,0.000000,0.500000,0.000000,0.00,0.00,1.00,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,0.0,0.0,0.0,0.0,1000.0,1,0.0,1,0.0,...,0.0,0.000000,0.250000,0.500000,0.000000,0.00,0.00,1.00,0.000000,0.000000
39166,2015026785,0.0,0.0,0.0,0.0,3000.0,1,5000.0,1,0.0,...,0.0,0.000000,0.500000,0.500000,0.250000,0.25,0.50,1.00,0.000000,0.000000
39167,2017040009,0.0,0.0,0.0,1.0,10000.0,2,0.0,1,0.0,...,1.0,0.000000,0.000000,0.500000,0.000000,0.00,0.50,1.00,0.000000,0.500000
39168,201100379,0.0,1.0,1.0,0.0,10000.0,2,15000.0,2,0.0,...,2.0,0.333333,0.000000,0.333333,0.333333,0.00,1.00,1.00,0.333333,0.666667
39169,2017040011,0.0,0.0,0.0,0.0,0.0,1,0.0,1,0.0,...,0.0,0.000000,0.333333,0.666667,0.666667,0.00,0.00,1.00,0.000000,0.000000

## 5.2 持有变量生成

In [51]:
from DataProcessor import creatnewvar

In [52]:
df13 = creatnewvar.hold_var(df12,sheet)

In [53]:
df13

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,住房公积金量占比,现金,活期存款,定期存款,互联网理财,债券,衍生品,非人民币资产,黄金,其他金融资产
0,2017000001,0.0,0.0,0.0,0,300.0,1,0.0,1,0.0,...,0.000000,1,0,0,0,0,0,0,0,0
1,2013013417,0.0,0.0,0.0,0,25000.0,4,3204.0,1,0.0,...,0.000000,1,1,0,0,0,0,0,0,0
2,2017000003,0.0,0.0,0.0,0,1700.0,1,5500.0,1,0.0,...,0.000000,1,1,0,0,0,0,0,0,0
3,2013012670,0.0,0.0,0.0,0,2000.0,1,7000.0,1,0.0,...,0.000000,1,1,0,0,0,0,0,0,0
4,2013020230,0.0,0.0,0.0,0,1000.0,1,26.0,1,0.0,...,0.000000,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,0.0,0.0,0.0,0,1000.0,1,0.0,1,0.0,...,0.000000,1,0,0,0,0,0,0,0,0
39166,2015026785,0.0,0.0,0.0,0,3000.0,1,5000.0,1,0.0,...,0.000000,1,1,0,0,0,0,0,0,0
39167,2017040009,0.0,0.0,0.0,1,10000.0,2,0.0,1,0.0,...,0.500000,1,0,0,1,0,0,0,0,0
39168,201100379,0.0,1.0,1.0,0,10000.0,2,15000.0,2,0.0,...,0.666667,1,1,0,1,0,0,0,0,0
39169,2017040011,0.0,0.0,0.0,0,0.0,1,0.0,1,0.0,...,0.000000,0,0,0,0,0,0,0,0,0

## 5.3 其他变量生成

In [54]:
#其他变量
df13['年龄'] = 2019-df13['年龄']
df13['受教育年限'] = df13['文化程度'].replace({1:0,2:6,3:9,4:12,5:12,6:15,7:16,8:18,9:22})
df13['转移收入'] = df13['父母转移收入'] + df13['父母2转移收入'] + df13['其他转移收入']

In [55]:
# 资产划分和占比
fengxian = df13[['股票', '基金', '金融理财',  '互联网理财', '债券', '衍生品', '非人民币资产', '黄金', '其他金融资产']]
cunkuan = df13[['活期存款', '定期存款']]
df13['风险'] = [1 if x >=1 else 0 for x in list(sum(fengxian.T.values)) ]
df13['存款'] = [1 if x >=1 else 0 for x in list(sum(cunkuan.T.values)) ]

df13['只风险'] = [1 if (df13['风险'][i]==1)&(df13['存款'][i] !=1) else 0 for i in range(len(df13['风险']))]
df13['只存款'] = [1 if (df13['风险'][i]!=1)&(df13['存款'][i] ==1) else 0 for i in range(len(df13['风险']))]
df13['均持有'] = [1 if (df13['风险'][i]==1)&(df13['存款'][i] ==1) else 0 for i in range(len(df13['风险']))]
df13['均不持有'] = [1 if (df13['风险'][i]!=1)&(df13['存款'][i] !=1) else 0 for i in range(len(df13['风险']))]


df13['金融资产总量tmp'] = 0
for i in ['活期存款量',  '定期存款量', 
    '股票量', '基金量',  '互联网理财量',  '金融理财量', '债券量', '衍生品量',  '非人民币资产量', '黄金量',  '其他金融资产量']:
    df13['金融资产总量tmp'] = df13['金融资产总量tmp'] + df13[i]

df13['风险金融资产总量tmp'] = 0
for i in [ '股票量', '基金量',  '互联网理财量',  '金融理财量', '债券量', '衍生品量',  '非人民币资产量', '黄金量',  '其他金融资产量']:
    df13['风险金融资产总量tmp'] = df13['风险金融资产总量tmp'] + df13[i]
df13['风险金融资产量占比'] = df13['风险金融资产总量tmp']/ df13['金融资产总量tmp']

df13['存款金融资产总量tmp'] = 0
for i in [ '活期存款量',  '定期存款量']:
    df13['存款金融资产总量tmp'] = df13['存款金融资产总量tmp'] + df13[i]
df13['存款金融资产量占比'] = df13['存款金融资产总量tmp']/ df13['金融资产总量tmp']

df13.fillna(0,inplace=True)

In [56]:
df13

,hhid,股票,基金,金融理财,借出款,现金量,现金量it,活期存款量,活期存款量it,定期存款量,...,存款,只风险,只存款,均持有,均不持有,金融资产总量tmp,风险金融资产总量tmp,风险金融资产量占比,存款金融资产总量tmp,存款金融资产量占比
0,2017000001,0.0,0.0,0.0,0,300.0,1,0.0,1,0.0,...,0,0,0,0,1,0.0,0.0,0.000000,0.0,0.000000
1,2013013417,0.0,0.0,0.0,0,25000.0,4,3204.0,1,0.0,...,1,0,1,0,0,3204.0,0.0,0.000000,3204.0,1.000000
2,2017000003,0.0,0.0,0.0,0,1700.0,1,5500.0,1,0.0,...,1,0,1,0,0,5500.0,0.0,0.000000,5500.0,1.000000
3,2013012670,0.0,0.0,0.0,0,2000.0,1,7000.0,1,0.0,...,1,0,1,0,0,7000.0,0.0,0.000000,7000.0,1.000000
4,2013020230,0.0,0.0,0.0,0,1000.0,1,26.0,1,0.0,...,1,0,1,0,0,26.0,0.0,0.000000,26.0,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,0.0,0.0,0.0,0,1000.0,1,0.0,1,0.0,...,0,0,0,0,1,0.0,0.0,0.000000,0.0,0.000000
39166,2015026785,0.0,0.0,0.0,0,3000.0,1,5000.0,1,0.0,...,1,0,1,0,0,5000.0,0.0,0.000000,5000.0,1.000000
39167,2017040009,0.0,0.0,0.0,1,10000.0,2,0.0,1,0.0,...,0,1,0,0,0,35000.0,35000.0,1.000000,0.0,0.000000
39168,201100379,0.0,1.0,1.0,0,10000.0,2,15000.0,2,0.0,...,1,0,0,1,0,91500.0,76500.0,0.836066,15000.0,0.163934
39169,2017040011,0.0,0.0,0.0,0,0.0,1,0.0,1,0.0,...,0,0,0,0,1,0.0,0.0,0.000000,0.0,0.000000

In [57]:
df_final = df13[[
#hhid
'hhid',
#各类金融资产是否持有
 '股票', '基金', '金融理财', '借出款', '现金', '活期存款', '定期存款', '互联网理财', '债券', '衍生品', '非人民币资产', '黄金', '其他金融资产',

#各类金融资产持有量+it
'现金量', '现金量it', '活期存款量', '活期存款量it', '定期存款量', '定期存款量it', '股票量', '股票量it', '基金量', '基金量it',
 '互联网理财量', '互联网理财量it', '金融理财量', '金融理财量it', '债券量', '债券量it', '衍生品量', '衍生品量it', '非人民币资产量', '非人民币资产量it', '黄金量', '黄金量it', '其他金融资产量', '其他金融资产量it', '借出款量', '借出款量it', 
#风险金融资产持有情况+占比
'风险', '存款', '只风险', '只存款', '均持有', '均不持有', '风险金融资产量占比', '存款金融资产量占比',  

#个人基本特征
'性别', '年龄', '婚姻', '文化程度','受教育年限',  '党员', '是否工作', '健康', '工作性质','文化程度_箱','户口（农村）_箱',  '健康_箱',
#个人其他

#支付工具持有（非现金）
 '信用卡持有', '借记卡持有', '电脑支付持有', '手机支付持有',
#个人主观
#  '是否关注经济金融信息', 
 '是否关注经济金融信息_箱','利率计算', '膨胀计算', '股票风险对比', '基金风险对比',  '幸福度', '风险态度', '投资经验1',
 '幸福度_箱', '风险态度_箱', 

# 家庭
#家庭基本特征
 '家庭规模', '家中老人数量', '家中小孩数量', '男性数量', '不健康人数', '政府工作人员', 
 '家中老人数量占比', '家中小孩数量占比', '男性数量占比', '不健康人数占比', '政府工作人员占比', 

 #家庭资产
'家庭总资产', '家庭总收入','工资收入', '农业收入', '转移收入', '工商业收入',  '农业机械价值', '车辆价值', '房产价值', '土地价值', '工商业价值','工商业经营生产活动', '家庭是否贫困', 
# '是否自有住房',

# 家庭消费
'家庭总消费', '食物支出', '教育培训支出', '衣着支出', '居住支出',  '医疗保健支出', '旅游支出','日用品支出', '文娱支出', '网购支出',

#家庭负债
'家庭负债',  '金融负债', '农业负债', '工商业负债', '房屋负债',  '车辆负债', '其他非金融负债', '教育负债',  '医疗负债', '其他负债',

#家庭需求流动性约束
 '养老保险量', '医疗保险量', '失业保险量', '住房公积金量', 
 '养老保险量占比', '医疗保险量占比', '失业保险量占比', '住房公积金量占比',

#地区
 '城乡', '省份'

]]

In [58]:
df_final.to_csv(r'data17.csv',encoding='utf_8_sig',index=False)

In [59]:
df_final

,hhid,股票,基金,金融理财,借出款,现金,活期存款,定期存款,互联网理财,债券,...,养老保险量,医疗保险量,失业保险量,住房公积金量,养老保险量占比,医疗保险量占比,失业保险量占比,住房公积金量占比,城乡,省份
0,2017000001,0.0,0.0,0.0,0,1,0,0,0,0,...,0.0,2.0,0.0,0.0,0.00,1.00,0.000000,0.000000,1,广东省
1,2013013417,0.0,0.0,0.0,0,1,1,0,0,0,...,3.0,4.0,0.0,0.0,0.75,1.00,0.000000,0.000000,0,福建省
2,2017000003,0.0,0.0,0.0,0,1,1,0,0,0,...,2.0,2.0,1.0,0.0,1.00,1.00,0.500000,0.000000,0,广西壮族自治区
3,2013012670,0.0,0.0,0.0,0,1,1,0,0,0,...,2.0,3.0,0.0,0.0,0.50,0.75,0.000000,0.000000,1,福建省
4,2013020230,0.0,0.0,0.0,0,1,1,0,0,0,...,0.0,4.0,0.0,0.0,0.00,1.00,0.000000,0.000000,1,广东省
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39165,2017040007,0.0,0.0,0.0,0,1,0,0,0,0,...,0.0,4.0,0.0,0.0,0.00,1.00,0.000000,0.000000,1,河南省
39166,2015026785,0.0,0.0,0.0,0,1,1,0,0,0,...,2.0,4.0,0.0,0.0,0.50,1.00,0.000000,0.000000,0,广东省
39167,2017040009,0.0,0.0,0.0,1,1,0,0,1,0,...,1.0,2.0,0.0,1.0,0.50,1.00,0.000000,0.500000,0,山东省
39168,201100379,0.0,1.0,1.0,0,1,1,0,1,0,...,3.0,3.0,1.0,2.0,1.00,1.00,0.333333,0.666667,0,北京市
39169,2017040011,0.0,0.0,0.0,0,0,0,0,0,0,...,0.0,3.0,0.0,0.0,0.00,1.00,0.000000,0.000000,0,河南省